### ISSUE TITLE
Pattern rewrite triggers index-out-of-bounds panic

### ISSUE THREAD

**Issue by rosekunkel** [egraphs-good/egg#129]
One of the rewrites I'm trying to use causes egg to panic when passing it to `Runner::run()`. I've attached the error and backtrace below. It seems to point to this line: https://github.com/egraphs-good/egg/blob/main/src/machine.rs#L331. The rewrite which triggers the error looks like this:
```text
(+ ?x0 ?x1 ?x2 ?x3) => (lib (λ (λ (λ (λ (+ $0 $1 $2 $3))))) (@ (@ (@ (@ $0 ?x3) ?x2) ?x1) ?x0))
```
I can provide more context if necessary.

```text
thread 'main' panicked at 'index out of bounds: the len is 4 but the index is 4', /home/rose/.cargo/git/checkouts/egg-f0b14e4f1101d956/b4257e8/src/machine.rs:76:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:92:14
   2: core::panicking::panic_bounds_check
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:69:5
   3: <usize as core::slice::index::SliceIndex<[T]>>::index
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/slice/index.rs:184:10
   4: core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/slice/index.rs:15:9
   5: <alloc::vec::Vec<T,A> as core::ops::index::Index<I>>::index
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/alloc/src/vec/mod.rs:2432:9
   6: egg::machine::Machine::reg
             at /home/rose/.cargo/git/checkouts/egg-f0b14e4f1101d956/b4257e8/src/machine.rs:76:9
   7: egg::machine::Program<L>::run::{{closure}}::{{closure}}
             at /home/rose/.cargo/git/checkouts/egg-f0b14e4f1101d956/b4257e8/src/machine.rs:331:45
   8: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ops/function.rs:280:13
   9: core::option::Option<T>::map
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/option.rs:823:29
  10: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/iter/adapters/map.rs:101:9
  11: <smallvec::SmallVec<A> as core::iter::traits::collect::Extend<<A as smallvec::Array>::Item>>::extend
             at /home/rose/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.7.0/src/lib.rs:1739:36
  12: <smallvec::SmallVec<A> as core::iter::traits::collect::FromIterator<<A as smallvec::Array>::Item>>::from_iter
             at /home/rose/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.7.0/src/lib.rs:1724:9
  13: core::iter::traits::iterator::Iterator::collect
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/iter/traits/iterator.rs:1749:9
  14: egg::machine::Program<L>::run::{{closure}}
             at /home/rose/.cargo/git/checkouts/egg-f0b14e4f1101d956/b4257e8/src/machine.rs:327:33
  15: egg::machine::Machine::run
             at /home/rose/.cargo/git/checkouts/egg-f0b14e4f1101d956/b4257e8/src/machine.rs:108:9
  16: egg::machine::Machine::run::{{closure}}
             at /home/rose/.cargo/git/checkouts/egg-f0b14e4f1101d956/b4257e8/src/machine.rs:97:25
  17: core::iter::traits::iterator::Iterator::for_each::call::{{closure}}
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/iter/traits/iterator.rs:734:29
  18: core::iter::adapters::filter::filter_fold::{{closure}}
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/iter/adapters/filter.rs:37:44
  19: core::iter::traits::iterator::Iterator::fold
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/iter/traits/iterator.rs:2174:21
  20: <core::iter::adapters::filter::Filter<I,P> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/iter/adapters/filter.rs:101:9
  21: core::iter::traits::iterator::Iterator::for_each
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/iter/traits/iterator.rs:737:9
  22: egg::machine::for_each_matching_node
             at /home/rose/.cargo/git/checkouts/egg-f0b14e4f1101d956/b4257e8/src/machine.rs:38:9
  23: egg::machine::Machine::run
             at /home/rose/.cargo/git/checkouts/egg-f0b14e4f1101d956/b4257e8/src/machine.rs:94:28
  24: egg::machine::Program<L>::run
             at /home/rose/.cargo/git/checkouts/egg-f0b14e4f1101d956/b4257e8/src/machine.rs:322:9
  25: <egg::pattern::Pattern<L> as egg::rewrite::Searcher<L,A>>::search_eclass
             at /home/rose/.cargo/git/checkouts/egg-f0b14e4f1101d956/b4257e8/src/pattern.rs:252:22
  26: <egg::pattern::Pattern<L> as egg::rewrite::Searcher<L,A>>::search::{{closure}}
             at /home/rose/.cargo/git/checkouts/egg-f0b14e4f1101d956/b4257e8/src/pattern.rs:240:43
  27: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ops/function.rs:269:13
  28: core::iter::traits::iterator::Iterator::find_map::check::{{closure}}
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/iter/traits/iterator.rs:2411:32
  29: core::iter::traits::iterator::Iterator::try_fold
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/iter/traits/iterator.rs:1998:21
  30: core::iter::traits::iterator::Iterator::find_map
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/iter/traits/iterator.rs:2417:9
  31: <core::iter::adapters::filter_map::FilterMap<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/iter/adapters/filter_map.rs:61:9
  32: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/alloc/src/vec/spec_from_iter_nested.rs:23:32
  33: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/alloc/src/vec/spec_from_iter.rs:33:9
  34: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/alloc/src/vec/mod.rs:2453:9
  35: core::iter::traits::iterator::Iterator::collect
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/iter/traits/iterator.rs:1749:9
  36: <egg::pattern::Pattern<L> as egg::rewrite::Searcher<L,A>>::search
             at /home/rose/.cargo/git/checkouts/egg-f0b14e4f1101d956/b4257e8/src/pattern.rs:238:34
  37: egg::rewrite::Rewrite<L,N>::search
             at /home/rose/.cargo/git/checkouts/egg-f0b14e4f1101d956/b4257e8/src/rewrite.rs:83:9
  38: <egg::run::BackoffScheduler as egg::run::RewriteScheduler<L,N>>::search_rewrite
             at /home/rose/.cargo/git/checkouts/egg-f0b14e4f1101d956/b4257e8/src/run.rs:810:23
  39: egg::run::Runner<L,N,IterData>::run_one::{{closure}}::{{closure}}
             at /home/rose/.cargo/git/checkouts/egg-f0b14e4f1101d956/b4257e8/src/run.rs:475:26
  40: core::iter::traits::iterator::Iterator::try_for_each::call::{{closure}}
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/iter/traits/iterator.rs:2056:26
  41: core::iter::traits::iterator::Iterator::try_fold
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/iter/traits/iterator.rs:1998:21
  42: core::iter::traits::iterator::Iterator::try_for_each
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/iter/traits/iterator.rs:2059:9
  43: egg::run::Runner<L,N,IterData>::run_one::{{closure}}
             at /home/rose/.cargo/git/checkouts/egg-f0b14e4f1101d956/b4257e8/src/run.rs:474:13
  44: core::result::Result<T,E>::and_then
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/result.rs:948:22
  45: egg::run::Runner<L,N,IterData>::run_one
             at /home/rose/.cargo/git/checkouts/egg-f0b14e4f1101d956/b4257e8/src/run.rs:473:18
  46: egg::run::Runner<L,N,IterData>::run
             at /home/rose/.cargo/git/checkouts/egg-f0b14e4f1101d956/b4257e8/src/run.rs:376:24
  47: smiley::main
             at ./src/bin/smiley/main.rs:79:22
  48: core::ops::function::FnOnce::call_once
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ops/function.rs:227:5
```

**Comment by rosekunkel** [comment]
I've pushed the code that triggers it to a new branch: https://github.com/dcao/babble/tree/egg-panic
To reproduce, run
```
cargo run --bin=smiley -- examples/nested-functions.bab
```

**Comment by rosekunkel** [comment]
I'll see if I can reduce the code

**Comment by rosekunkel** [comment]
While reducing it, I found a bug in my code that I think is responsible for the issue - I was assuming that nodes with the same operation have the same number of children. Fixing that makes the code no longer panic.

**Comment by robert-chiniquy** [comment]
Hmm, I just hit this one somehow, maybe I am making the same mistake somehow ... this is happening with an N-ary operator ...

**Comment by mtak-** [comment]
@robert-chiniquy I've hit similar panics with n-ary operators. My issue was fixed by checking that `lhs.children().len() == rhs.children().len()` inside of `matches`.

@mwillsey Could arity be checked within `egg` itself? Perhaps mentioning arity in the documentation for `matches` would help.

```
Returns true if this enode matches another enode. This should only consider the operator **and arity**, not the children Ids.
```

**Comment by mwillsey** [comment]
Yes, that seems like a reasonable change, I'll add that to the docs.

**Comment by robert-chiniquy** [comment]
Awesome, thanks for the tip! I was missing that.
